[2025-03-28T07:29:34.570+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T07:29:34.586+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_nyc_taxi_dag.run_nyc_taxi_spark_job manual__2025-03-28T07:28:31.530318+00:00 [queued]>
[2025-03-28T07:29:34.592+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_nyc_taxi_dag.run_nyc_taxi_spark_job manual__2025-03-28T07:28:31.530318+00:00 [queued]>
[2025-03-28T07:29:34.592+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-28T07:29:34.600+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): run_nyc_taxi_spark_job> on 2025-03-28 07:28:31.530318+00:00
[2025-03-28T07:29:34.608+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=92) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-28T07:29:34.609+0000] {standard_task_runner.py:72} INFO - Started process 93 to run task
[2025-03-28T07:29:34.609+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_nyc_taxi_dag', 'run_nyc_taxi_spark_job', 'manual__2025-03-28T07:28:31.530318+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/rill_pipeline.py', '--cfg-path', '/tmp/tmpt2w0bnqi']
[2025-03-28T07:29:34.610+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask run_nyc_taxi_spark_job
[2025-03-28T07:29:34.646+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_nyc_taxi_dag.run_nyc_taxi_spark_job manual__2025-03-28T07:28:31.530318+00:00 [running]> on host 4517e84523fd
[2025-03-28T07:29:34.710+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_nyc_taxi_dag' AIRFLOW_CTX_TASK_ID='run_nyc_taxi_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T07:28:31.530318+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T07:28:31.530318+00:00'
[2025-03-28T07:29:34.711+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-28T07:29:34.729+0000] {spark_submit.py:305} INFO - Could not load connection string spark_default, defaulting to yarn
[2025-03-28T07:29:34.730+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --num-executors 2 --executor-cores 2 --executor-memory 2g --driver-memory 2g --name arrow-spark /opt/***/dags/spark_jobs.zip spark_jobs.jobs.nyc_taxi
[2025-03-28T07:29:34.772+0000] {spark_submit.py:645} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-03-28T07:29:34.773+0000] {spark_submit.py:645} INFO - JAVA_HOME is not set
[2025-03-28T07:29:34.782+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --num-executors 2 --executor-cores 2 --executor-memory 2g --driver-memory 2g --name arrow-spark /opt/***/dags/spark_jobs.zip spark_jobs.jobs.nyc_taxi. Error code is: 1.
[2025-03-28T07:29:34.786+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=spark_nyc_taxi_dag, task_id=run_nyc_taxi_spark_job, run_id=manual__2025-03-28T07:28:31.530318+00:00, execution_date=20250328T072831, start_date=20250328T072934, end_date=20250328T072934
[2025-03-28T07:29:34.806+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-28T07:29:34.807+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task run_nyc_taxi_spark_job (Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --num-executors 2 --executor-cores 2 --executor-memory 2g --driver-memory 2g --name arrow-spark /opt/***/dags/spark_jobs.zip spark_jobs.jobs.nyc_taxi. Error code is: 1.; 93)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --num-executors 2 --executor-cores 2 --executor-memory 2g --driver-memory 2g --name arrow-spark /opt/***/dags/spark_jobs.zip spark_jobs.jobs.nyc_taxi. Error code is: 1.
[2025-03-28T07:29:34.823+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-28T07:29:34.836+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-28T07:29:34.837+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
